### ISSUE TITLE
Input for Nbody-naive

### ISSUE THREAD

**Issue by TizianoDeMatteis** [diku-dk/CFAL-bench#1]
The current naive implementation of nbody-naive does not define input format (or provide example)

**Comment by athas** [comment]
[This is the input format](https://github.com/diku-dk/CFAL-bench/blob/079361450876732322fd55dfd1b7b9b663e69d0c/nbody-naive/nbody.c#L57).

**Comment by athas** [comment]
(Of the dummy implementation, anyway.)  Note that performance of a naive nbody only depends on `n`, not the actual particle values, so it may not be important to define an input format here.

**Comment by TizianoDeMatteis** [comment]
NVM, I will use random data.
Thanks!
